### ISSUE TITLE
Prevent angular component metadata mutation

### ISSUE THREAD

**Issue by simbas** [nicojs/angular-stryker-example#2]
Hello @nicojs ,

First of all, thank you for sharing this example repository.

for `app.component.ts` and `app.component.spec.ts`:
```typescript
// app.component.ts

import { Component } from '@angular/core';

@Component({
  selector: 'portal-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Portal';
}

// app.component.spec.ts

import { TestBed, async } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';
import { NO_ERRORS_SCHEMA } from '@angular/core';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      schemas: [NO_ERRORS_SCHEMA],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));
  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
  it(`should have as title 'Portal'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('Portal');
  }));
  it('should render title in a .title tag', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('.title').textContent).toContain('Portal');
  }));
});
```

Do you think it is possible to prevent stryker to mutate the angular component metadata?

```
Mutant survived!
/usr/src/app/src/app/app.component.ts:3:12
Mutator: StringLiteral
-     selector: 'portal-root',
+     selector: "",

Ran all tests for this mutant.
Mutant survived!
/usr/src/app/src/app/app.component.ts:5:13
Mutator: ArrayLiteral
-     styleUrls: ['./app.component.scss']
+     styleUrls: []
```

It doesn't seems relevant.

**Comment by nicojs** [comment]
Hi @simbas thanks for your feedback!

This issue makes me happy. The angular "metadata" (its not exactly metadata IMHO) is exactly the reason to use mutation testing. We can alter the styles url and selector without breaking any tests. So why is the code there? If it's useless code, it should be removed. If it's useful code it should tested. In this case:

* Indeed the styles url in this example could be removed. 
* The selector is required and thus I would expect it to be tested. You could for example create a unit test that verifies the selector name. Or you could create an integration test that creates an `<app>` element and makes sure the app is loaded correctly.

I will not change the code in this example project, because it uses the default angular-cli template. Apparently the default project everyone gets at the beginning has a low mutation score, they could fix that by adding some tests.

**Comment by simbas** [comment]
Hi @nicojs , thank you very much for your feedback.

Finally I removed the `stylesUrls` metadata and test the selector with:
```typescript
  it(`should be selected with 'portal-root' selector`, async(() => {
    const metadata = AppComponent['__annotations__'][0];
    expect(metadata.selector).toBe('portal-root');
  }));
```

I like your suggestion of an integration test that creates an `<portal-root>`. I will implement that test.

You have 100% convinced me about testing the component metadata.

Stryker is such an awesome tool  👍 .

**Comment by pedrotainha** [comment]
Hello @nicojs , I'm dealing with this situation also, but in my case, I need to make use of the "stylesUrls". 

With the example that @simbas provided I was not able to solve it because styleUrls will become "style" in the metadata.

Any idea how to achive a unit test for styleUrls? 
thanks in advance

**Comment by nicojs** [comment]
Since stryker-karma-runner 0.16.1, the angular cli is actually native supported. If you use that setup, the style urls changes are reported as a runtime error and thus ignored for mutation score calculation. 

See https://github.com/stryker-mutator/stryker/tree/master/packages/stryker-karma-runner#configure-angular-cli

Note: you need to update to angular cli 6.1.x for it to work.
